### Register new user
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "Zhaka Hidayat",
  "id": "zhaka",
  "password": "rahasia"
}

### Login user
POST http://localhost:3000/api/users/_login
Content-Type: application/json

{
  "id": "zhaka",
  "password": "rahasia"
}

### Get user profile
GET http://localhost:3000/api/users/_current
Accept: application/json
Authorization: {{token}}

### Logout user
DELETE http://localhost:3000/api/users
Accept: application/json
Authorization: {{token}}

### Update user
PATCH http://localhost:3000/api/users/_current
Content-Type: application/json
Accept: application/json
Authorization: {{token}}

{
  "name": "Zhaka H.Y"
}